### ISSUE TITLE
Manager run control GUI is confusing and abysmal.

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/NSCLDAQ#218]
Let's write  a new one based on what we've learned....maybe have it look a bit more like the ReadoutShell visually...with extras for the manager things.

**Comment by rfoxkendo** [comment]
A python/pyqt based run controller is now installed in $DAQBIN/mg_control.  The first time it's run in a specific directory, 
it brings up a wizard to configure it.   The wizard writes the file ```mg_guiconfig.toml``` and subsequent runs use that file to get the configuration.  

Sample:

```toml
[connection]
host = "localhost"
rest_service = "DAQManager"
monitor_service = "DAQManager-outputMonitor"

[programs]
readouts=['Squirter_readout']
```
The [connection] section should be pretty simple though the user, in production should not specify 'localhost' for the host. the manager runs in  [programs].readouts - is a list of programs the gui will monitor the status of.


pulling this code (rfoxkendo/issue218) in to the 12.1-dev branch.
